### ISSUE TITLE
Where is the Travis CI build status icon?

### ISSUE THREAD

**Issue by etiennedanis** [MOLB7621/problem-set-1#5]
Hello Team MOLB7621!

I just pushed my answers.sh and answers.yml files on Github.
I can't find the Travis CI build status icon that should turn green if the answers are correct.
If you could help me with that step, that would be fantastic.
Thank you very much in advance!
Best,
Etienne

**Comment by kriemo** [comment]
Hi Etienne,
  We will go over how to set up Travis on Tuesday. Briefly, these are the steps involved if you'd like to set it up beforehand:

1) Set up an account with [Travis](https://travis-ci.org/) using your github login
2) Once logged in to Travis, go to the Travis home home page (click your username in the top right corner). You should see your problem-set 1 repository listed at the bottom of the page 
3) Flick the repository switch to the on position for your forked problem-set 1 repository
4) Edit the first line of the `README.md` file in your cloned problem-set 1 repo, so that your username replaces `MOLB7621` in both URLs:

```bash
# original first line of README.md
[![Build Status](https://travis-ci.org/MOLB7621/problem-set-1.svg?branch=master)](https://travis-ci.org/MOLB7621/problem-set-1)

#edited line, note the two spots that are edited
[![Build Status](https://travis-ci.org/USERNAME/problem-set-1.svg?branch=master)](https://travis-ci.org/USERNAME/problem-set-1)
```

5) Commit and push the updated `README.md`, which should trigger Travis to check your work. Travis will "rebuild" your project and check your work with each new commit that is pushed to your forked repo.

**Comment by etiennedanis** [comment]
Thank you very much!
This was very useful!

Etienne
